# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
1.upto(20).map do |n|
  user = User.create!(
      [{id: n + 100,
      email: "#{n + 100}@example.com",
      password: 'topsecret',
      password_confirmation: 'topsecret',
    }]
  )
end
  profile = Profile.create!(
      [{id: 101,
      user_id: 101,
      username: 'Lauren',
      avatar: "1",
      about_me: "Hello!",
    },
      {id: 102,
      user_id: 102,
      username: 'Joe',
      avatar: "8",
      about_me: "What's up!",
    },
      {id: 103,
      user_id: 103,
      username: 'Jeff',
      avatar: "3",
      about_me: "Currently learning how to code!",
    },
      {id: 104,
      user_id: 104,
      username: 'Jack',
      avatar: "4",
      about_me: "Coding is awesome!",
    },
      {id: 105,
      user_id: 105,
      username: 'Samantha',
      avatar: "5",
      about_me: "Hi!",
    },
      {id: 106,
      user_id: 106,
      username: 'Tyler',
      avatar: "6",
      about_me: "Currently learning how to code!",
    },
      {id: 107,
      user_id: 107,
      username: 'Kevin',
      avatar: "7",
      about_me: "Hey!",
    },
      {id: 108,
      user_id: 108,
      username: 'Noah',
      avatar: "8",
      about_me: "Hi!",
    },
      {id: 109,
      user_id: 109,
      username: 'Liam',
      avatar: "9",
      about_me: "I'm a RoR developer from Fort Lauderdale!",
    },
      {id: 110,
      user_id: 110,
      username: 'Emma',
      avatar: "10",
      about_me: "Coding is awesome!",
    },
      {id: 111,
      user_id: 111,
      username: 'Olivia',
      avatar: "11",
      about_me: "Hi!",
    },
      {id: 112,
      user_id: 112,
      username: 'Mason',
      avatar: "1",
      about_me: "What's up!",
    },
      {id: 113,
      user_id: 113,
      username: 'Sophia',
      avatar: "10",
      about_me: "Hello! I am a self-taught web developer.
      I enjoy knitting, gardening, and cooking.",
    },
      {id: 114,
      user_id: 114,
      username: 'Jacob',
      avatar: "4",
      about_me: "Hey there!",
    },
      {id: 115,
      user_id: 115,
      username: 'Isabella',
      avatar: "5",
      about_me: "I love coding!",
    },
      {id: 116,
      user_id: 116,
      username: 'William',
      avatar: "6",
      about_me: "I am a senior web developer at a digital media marketing agency in Miami.
      I am here to give advice on front-end development!",
    },
      {id: 117,
      user_id: 117,
      username: 'Ava',
      avatar: "2",
      about_me: "Hi, I'm Ava! I'm currently studying theater and performance art
      at Nova Southeastern University. I have some experience in graphic design
      and would love to create my own websites!",
    },
      {id: 118,
      user_id: 118,
      username: 'Ethan',
      avatar: "8",
      about_me: "What's up! I'm currently studying Digital Communications & Media at NYU!
      I'm learning programming in my spare time.",
    },
      {id: 119,
      user_id: 119,
      username: 'Mia',
      avatar: "9",
      about_me: "I am a Ruby on Rails junior web-developer living in South Florida.
      I'm currently learning JavaScript and jQuery!",
    },
      {id: 120,
      user_id: 120,
      username: 'Michael',
      avatar: "7",
      about_me: "I enjoy traveling and learning how to program!",
    }]
  )
