# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
1.upto(20).map do |n|
  user = User.create!(
      [{id: n + 100,
      email: "#{n + 100}@example.com",
      password: 'topsecret',
      password_confirmation: 'topsecret',
    }]
  )
end
  profile = Profile.create!(
      [{id: 101,
      user_id: 101,
      username: 'john',
      avatar: "1",
      about_me: "Here's my about me section. I'm a seed!!!!",
    },
      {id: 102,
      user_id: 102,
      username: 'joe',
      avatar: "2",
      about_me: "Here's my about me section. I'm a seed!!!!",
    },
      {id: 103,
      user_id: 103,
      username: 'jeff',
      avatar: "3",
      about_me: "Here's my about me section. I'm a seed!!!!",
    },
      {id: 104,
      user_id: 104,
      username: 'jack',
      avatar: "4",
      about_me: "Here's my about me section. I'm a seed!!!!",
    },
      {id: 105,
      user_id: 105,
      username: 'joann',
      avatar: "5",
      about_me: "Here's my about me section. I'm a seed!!!!",
    },
      {id: 106,
      user_id: 106,
      username: 'juan',
      avatar: "6",
      about_me: "Here's my about me section. I'm a seed!!!!",
    },
      {id: 107,
      user_id: 107,
      username: 'alec',
      avatar: "7",
      about_me: "Here's my about me section. I'm a seed!!!!",
    },
      {id: 108,
      user_id: 108,
      username: 'noah',
      avatar: "8",
      about_me: "Here's my about me section. I'm a seed!!!!",
    },
      {id: 109,
      user_id: 109,
      username: 'liam',
      avatar: "9",
      about_me: "Here's my about me section. I'm a seed!!!!",
    },
      {id: 110,
      user_id: 110,
      username: 'emma',
      avatar: "10",
      about_me: "Here's my about me section. I'm a seed!!!!",
    },
      {id: 111,
      user_id: 111,
      username: 'olivia',
      avatar: "11",
      about_me: "Here's my about me section. I'm a seed!!!!",
    },
      {id: 112,
      user_id: 112,
      username: 'mason',
      avatar: "",
      about_me: "Here's my about me section. I'm a seed!!!!",
    },
      {id: 113,
      user_id: 113,
      username: 'sophia',
      avatar: "",
      about_me: "Here's my about me section. I'm a seed!!!!",
    },
      {id: 114,
      user_id: 114,
      username: 'jacob',
      avatar: "",
      about_me: "Here's my about me section. I'm a seed!!!!",
    },
      {id: 115,
      user_id: 115,
      username: 'isabella',
      avatar: "",
      about_me: "Here's my about me section. I'm a seed!!!!",
    },
      {id: 116,
      user_id: 116,
      username: 'william',
      avatar: "",
      about_me: "Here's my about me section. I'm a seed!!!!",
    },
      {id: 117,
      user_id: 117,
      username: 'ava',
      avatar: "",
      about_me: "Here's my about me section. I'm a seed!!!!",
    },
      {id: 118,
      user_id: 118,
      username: 'ethan',
      avatar: "",
      about_me: "Here's my about me section. I'm a seed!!!!",
    },
      {id: 119,
      user_id: 119,
      username: 'mia',
      avatar: "",
      about_me: "Here's my about me section. I'm a seed!!!!",
    },
      {id: 120,
      user_id: 120,
      username: 'michael',
      avatar: "",
      about_me: "Here's my about me section. I'm a seed!!!!",
    }]
  )
